# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  inputs,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nixpkgs.overlays = [inputs.nix-cachyos-kernel.overlays.pinned];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];

  boot.blacklistedKernelModules = [
    # Obscure network protocols
    "ax25" "netrom" "rose"
    # Old or rare or insufficiently audited filesystems
    "adfs" "affs" "bfs" "befs" "cifs" "cramfs" "efs" "exofs"
    "freevxfs" "gfs2" "hfs" "hfsplus" "hpfs" "jffs2" "jfs" "ksmbd"
    "minix" "nfsv4" "nfsv3" "nfs" "nilfs2" "omfs" "qnx4" "qnx6" "sysv"
    "udf" "ufs" "vivid" "floppy" "parport"
    # Something else
    "appletalk" "atm" "can" "dccp" "decnet" "econet"
    "ipx" "n-hdlc" "p8022" "p8023" "psnap"
    "rds" "sctp" "tipc" "x25"
    # Unused sensors
    "kfifo_buf" "cm32181"
    # Unused io
    "joydev" # joystick
    "mac_hid" # mac mouse
    # FireWire
    "firewire-core" "firewire-ohci" "firewire-sbp2"
  ];

  boot.kernelParams = [
    "mitigations=off"
    # Avoid touchpad click to tap (clickpad) bug. For more detail see:
    # https://wiki.archlinux.org/title/Touchpad_Synaptics#Touchpad_does_not_work_after_resuming_from_hibernate/suspend
    "psmouse.synaptics_intertouch=0"
  ];
  boot.kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-latest-lto-x86_64-v3;
  boot.extraModulePackages = [ ];

  boot.tmp = {
    cleanOnBoot = true;
    useTmpfs = true;
  };

  # Disk layout, fileSystems and swapDevices are defined in disko.nix.
  zramSwap.enable = true;
  services.scx.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
